### PR TITLE
[FLINK-33328] Allow TwoPhaseCommittingSink WithPreCommitTopology to alter the type of the Committable - mixin approach

### PR DESCRIPTION
**Pull request by pvary**
## What is the purpose of the change

Mixin based implementation for [FLIP-372](https://cwiki.apache.org/confluence/display/FLINK/FLIP-372%3A+Allow+TwoPhaseCommittingSink+WithPreCommitTopology+to+alter+the+type+of+the+Committable)

For now, just checking backward compatibility of the API changes

## Brief change log

- Moving inner classes to main classes:
    - `CommitterInitContext` from `Sink.CommitterInitContext` 
    - `CommittingSinkWriter` from `TwoPhaseCommittingSink.PrecommittingSinkWriter`
    -  `StatefulSinkWriter` from `StatefulSink.StatefulSinkWriter`
    - `WriterInitContext` from `Sink.InitContext`
- Moving to mixin interfaces:
   - `SupportsCommitter` from `TwoPhaseCommittingSink`
   - `SupportsWriterState` from `StatefulSink`
   - `SupportsPostCommitTopology` from `WithPostCommitToplogy`
   - `SupportsPreCommitTopology` from `WithPreCommitTopology`
   - `SupportsPreWriteTopology` from `WithPreWriteTopology`
- Deprecation methods with default implementations
- Few internal changes to make everything work

## Verifying this change

The CI will run all the tests to see if the change breaks anything

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: yes
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? yes
  - If yes, how is the feature documented? not documented

### CODE REVIEW

**Comment by pvary** [comment]
@flinkbot run azure

File: flink-core/src/main/java/org/apache/flink/api/connector/sink2/TwoPhaseCommittingSink.java [hunk 1]
```diff
@@ -40,17 +37,9 @@
...
-
-    /**
-     * Creates a {@link PrecommittingSinkWriter} that creates committables on checkpoint or end of
-     * input.
-     *
-     * @param context the runtime context.
-     * @return A sink writer for the two-phase commit protocol.
-     * @throws IOException for any failure during creation.
-     */
-    PrecommittingSinkWriter<InputT, CommT> createWriter(InitContext context) throws IOException;
```
Comment (leonardBang) [inline flink-core/src/main/java/org/apache/flink/api/connector/sink2/TwoPhaseCommittingSink.java:53]: We'd better save the method which is better than `SinkWriter<InputT, CommT> createWriter(InitContext context)` as it return a `PrecommittingSinkWriter` which contains more information than `SinkWriter`

Comment (pvary) [reply flink-core/src/main/java/org/apache/flink/api/connector/sink2/TwoPhaseCommittingSink.java:53]: @leonardBang: Thanks for the review!

This was the exact issue which prevented us to evolve the API.
`TwoPhaseCommittingSink` and `StatefulSink` overrides the same `createWriter` method with different return types. If we need to evolve the `createWriter` method for whatever reason in the future, then we need to provide a default implementation for it, and the new method to allow backward compatibility.
If there is a sink which implements both `TwoPhaseCommittingSink` and `StatefulSink`, then it will not implement the new method, so the default implementation will be inherited from both `TwoPhaseCommittingSink` and `StatefulSink` which will cause a java compilation error.

That is why we need to remove this method, and use `instanceof` instead in the implementation, to check the types.

Of course, I am open for any suggestion, but sadly nothing viable come up during the discussions on the dev list [1], [2]

Thanks,
[1] - https://lists.apache.org/thread/344pzbrqbbb4w0sfj67km25msp7hxlyd
[2] - https://lists.apache.org/thread/h6nkgth838dlh5s90sd95zd6hlsxwx57

Comment (leonardBang) [reply flink-core/src/main/java/org/apache/flink/api/connector/sink2/TwoPhaseCommittingSink.java:53]: Thanks @pvary for the explanation, makes sense to me.

File: flink-core/src/main/java/org/apache/flink/api/connector/sink2/Sink.java [hunk 2]
```diff
@@ -52,11 +54,30 @@ public interface Sink<InputT> extends Serializable {
...
      * @return A sink writer.
      * @throws IOException for any failure during creation.
+     * @deprecated Please implement {@link #createWriter(WriterInitContext)}. For backward
+     *     compatibility reasons - to keep {@link Sink} a functional interface - Flink did not
+     *     provide a default implementation. New {@link Sink} implementations should implement this
+     *     method, but it will not be used, and it will be removed in 1.20.0 release. Do not use
+     *     {@link Override} annotation when implementing this method, to prevent compilation errors
+     *     when migrating to 1.20.x release.
      */
+    @Deprecated
```
Comment (rodmeneses) [inline flink-core/src/main/java/org/apache/flink/api/connector/sink2/Sink.java:64]: do we use the attribute option `since` in other places? it might be useful to have that in the annotation itself

File: flink-core/src/main/java/org/apache/flink/api/connector/sink2/StatefulSink.java [hunk 3]
```diff
@@ -36,49 +34,43 @@
  * @param <WriterStateT> The type of the sink writer's state
  */
 @PublicEvolving
-public interface StatefulSink<InputT, WriterStateT> extends Sink<InputT> {
+@Deprecated
```
Comment (rodmeneses) [inline flink-core/src/main/java/org/apache/flink/api/connector/sink2/StatefulSink.java:37]: we could add reason for deprecation in the java doc of this interface

File: flink-core/src/main/java/org/apache/flink/api/connector/sink2/SupportsWriterState.java [hunk 4]
```diff
@@ -0,0 +1,72 @@
...
+ * @param <InputT> The type of the sink's input
+ * @param <WriterStateT> The type of the sink writer's state
+ */
+@PublicEvolving
+public interface SupportsWriterState<InputT, WriterStateT> {
+
+    /**
+     * Create a {@link StatefulSinkWriter} from a recovered state.
+     *
+     * @param context the runtime context.
```
Comment (rodmeneses) [inline flink-core/src/main/java/org/apache/flink/api/connector/sink2/SupportsWriterState.java:43]: nit: Java doc doesn't include second parameter `recoveredState`

File: flink-core/src/main/java/org/apache/flink/api/connector/sink2/SupportsWriterState.java [hunk 5]
```diff
@@ -0,0 +1,72 @@
...
+    SimpleVersionedSerializer<WriterStateT> getWriterStateSerializer();
+
+    /**
+     * A mix-in for {@link SupportsWriterState} that allows users to migrate from a sink with a
+     * compatible state to this sink.
+     */
+    @PublicEvolving
+    interface WithCompatibleState {
+        /**
+         * A list of state names of sinks from which the state can be restored. For example, the new
```
Comment (rodmeneses) [inline flink-core/src/main/java/org/apache/flink/api/connector/sink2/SupportsWriterState.java:66]: nit: `A collection of state...`

File: flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/WithPreWriteTopology.java [hunk 6]
```diff
@@ -21,18 +21,9 @@
...
-    /**
-     * Adds an arbitrary topology before the writer. The topology may be used to repartition the
-     * data.
-     *
-     * @param inputDataStream the stream of input records.
-     * @return the custom topology before {@link SinkWriter}.
-     */
-    DataStream<InputT> addPreWriteTopology(DataStream<InputT> inputDataStream);
-}
+@Deprecated
```
Comment (rodmeneses) [inline flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/WithPreWriteTopology.java:27]: we could explain in the javadoc why this interface is deprecated, specially since it's a new addition

File: flink-core/src/main/java/org/apache/flink/api/connector/sink2/Sink.java (hunk 2 above)
Comment (pvary) [reply flink-core/src/main/java/org/apache/flink/api/connector/sink2/Sink.java:64]: `since` is only supported since java9. The code should be compatible with java8, so we can not use `since` yet.

File: flink-core/src/main/java/org/apache/flink/api/connector/sink2/SupportsWriterState.java (hunk 5 above)
Comment (pvary) [reply flink-core/src/main/java/org/apache/flink/api/connector/sink2/SupportsWriterState.java:66]: Fixed in #24022

File: flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/WithPreWriteTopology.java (hunk 6 above)
Comment (pvary) [reply flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/WithPreWriteTopology.java:27]: Added the `@deprecated` in #24022

**Comment by pvary** [comment]
We merged this in several smaller parts
