### PR TITLE
[FLINK-2231] Create a Serializer for Scala Enumerations.

### PR DESCRIPTION
**Pull request by aalexandrov**
This closes FLINK-2231.

The code should work for all objects which follow [the Enumeration idiom outlined in the ScalaDoc](http://www.scala-lang.org/api/2.11.5/index.html#scala.Enumeration).

The second commit fixes a compilation error in IntelliJ when the 'scala_2.11' profile is active.

The third commit removes the boilerplate code from the `EnumValueComparator` by delegating to an `IntComparator`, you can either discard or squash it while merging depending on your preference.

Bear in mind the FIXME at line 370 in `TypeAnalyzer.scala`. The commented out code is better, but unfortunately doesn't work with Scala 2.10, so I used the FQN workaround.

### CODE REVIEW

**Comment by aalexandrov** [comment]
PS. The third commit fixes a compilation error in IntelliJ when the 'scala_2.11' profile is active.

File: flink-tests/src/test/scala/org/apache/flink/api/scala/runtime/ScalaSpecialTypesSerializerTest.scala [hunk 1]
```diff
@@ -93,8 +98,11 @@ class ScalaSpecialTypesSerializerTest {
       val typeInfo = implicitly[TypeInformation[T]]
       val serializer = typeInfo.createSerializer(new ExecutionConfig)
       val typeClass = typeInfo.getTypeClass
-      val test =
+      val test = if (typeInfo.isInstanceOf[EnumValueTypeInfo[_]]) {
+        new ScalaSpecialTypesSerializerTestInstance[T](serializer, typeClass, 4, instances)
```
Comment (aljoscha) [inline flink-tests/src/test/scala/org/apache/flink/api/scala/runtime/ScalaSpecialTypesSerializerTest.scala]: We could use serializer.getLength here.

**Comment by aljoscha** [comment]
Looks good, any objections to me merging this? I can fix the one comment I had about using serializer.getLength when I merge it.

File: flink-scala/src/main/scala/org/apache/flink/api/scala/typeutils/EnumValueSerializer.scala [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+
+  override def copy(src: DataInputView, tgt: DataOutputView): Unit = intSerializer.copy(src, tgt)
+
+  override def serialize(v: T, tgt: DataOutputView): Unit = intSerializer.serialize(v.id, tgt)
+
+  override def deserialize(source: DataInputView): T = enum(intSerializer.deserialize(source))
+
+  override def deserialize(reuse: T, source: DataInputView): T = deserialize(source)
+
+  override def equals(obj: Any): Boolean = {
```
Comment (StephanEwen) [inline flink-scala/src/main/scala/org/apache/flink/api/scala/typeutils/EnumValueSerializer.scala]: Can you also override `hashCode()` here? Keeps it consistent with overriding `equals()`

**Comment by StephanEwen** [comment]
Other than the one comment, this looks good.

+1

**Comment by aljoscha** [comment]
Merged, thanks for your work. :smile:
