### PR TITLE
[FLINK-19934][Connector] Add a new API: SplitEnumeratorContext.runInC…

### PR DESCRIPTION
**Pull request by stevenzwu**
…oordinatorThread(Runnable)

## What is the purpose of the change

This PR adds a new API in SplitEnumeratorContext so that enumerator can run all actions in the source coordinator thread.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (yes)
  - If yes, how is the feature documented? (JavaDocs)

### CODE REVIEW

**Comment by StephanEwen** [comment]
+1 from my side

@becketqin Unless you have any concerns, I'd merge this before the feature freeze.

**Comment by becketqin** [comment]
+1. No concerns from my side.

**Comment by tillrohrmann** [comment]
I think this PR breaks the master @StephanEwen because `MockSplitEnumeratorContext` does not implement `SplitEnumeratorContext.runInCoordinatorThread`.

**Comment by tillrohrmann** [comment]
Sorry I think the problem was introduced with #13574.

**Comment by tillrohrmann** [comment]
I've fixed the problem with a1ec69a75f7e3512b8de698619d53f5d89897973
