### PR TITLE
[FLINK-34204][core] spotless:apply

### PR DESCRIPTION
**Pull request by XComp**
Compilation error fix that was introduced with https://github.com/apache/flink/commit/84444d50 in the JDK17 profile (parent PR #24187)

[Related CI failure](https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=57007&view=logs&j=f693abc3-390c-511e-7162-44da4abb3b05&t=0150d857-6b31-59f6-0d5b-ddbf998e32ad)

### CODE REVIEW

**Comment by XComp** [comment]
The compile step succeeded. I'm gonna go ahead and stabilize master w/o approval.
