### PR TITLE
[FLINK-12115] [filesystems]: Add support for AzureFS

### PR DESCRIPTION
**Pull request by piyushnarang**
## What is the purpose of the change

Add support for the Azure blob store as one of the supported flink-filesystems. 

## Brief change log

* Add Azure FS factory and file system class. 

## Verifying this change

This change added tests and can be verified as follows:

  - *Added unit tests*
  - *Added file system integration tests for HTTP / HTTPs schemes*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): yes (hadoop-azure)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? yes
  - If yes, how is the feature documented? Javadocs

### CODE REVIEW

File: flink-filesystems/flink-azure-fs-hadoop/src/main/java/org/apache/flink/fs/azurefs/AbstractAzureFSFactory.java [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+	private Configuration flinkConfig;
+
+	@Override
+	public void configure(Configuration config) {
+		flinkConfig = config;
+	}
+
+	@Override
+	public FileSystem create(URI fsUri) throws IOException {
+		checkNotNull(fsUri, "fsUri");
```
Comment (Myasuka) [inline flink-filesystems/flink-azure-fs-hadoop/src/main/java/org/apache/flink/fs/azurefs/AbstractAzureFSFactory.java]: How about messages with more hints?

File: flink-filesystems/flink-azure-fs-hadoop/src/test/java/org/apache/flink/fs/azurefs/AzureFileSystemBehaviorITCase.java [hunk 2]
```diff
@@ -0,0 +1,193 @@
...
+	private static final String CONTAINER = System.getenv("ARTIFACTS_AZURE_CONTAINER");
+	private static final String ACCOUNT = System.getenv("ARTIFACTS_AZURE_STORAGE_ACCOUNT");
+	private static final String ACCESS_KEY = System.getenv("ARTIFACTS_AZURE_ACCESS_KEY");
+
+	private static final String TEST_DATA_DIR = "tests-" + UUID.randomUUID();
+
+	@BeforeClass
+	public static void checkCredentialsAndSetup() throws IOException {
+		// check whether credentials and container / account details exist
+		Assume.assumeTrue("Azure storage account not configured, skipping test...", ACCOUNT != null);
```
Comment (Myasuka) [inline flink-filesystems/flink-azure-fs-hadoop/src/test/java/org/apache/flink/fs/azurefs/AzureFileSystemBehaviorITCase.java]: How about use `StringUtils#isNullOrWhitespaceOnly` to check? the same for below.

File: flink-filesystems/flink-azure-fs-hadoop/src/main/java/org/apache/flink/fs/azurefs/AbstractAzureFSFactory.java [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+ * the correct scheme (wasb / wasbs).
+ */
+public abstract class AbstractAzureFSFactory implements FileSystemFactory {
+	private static final Logger LOG = LoggerFactory.getLogger(AzureFSFactory.class);
+
+	private Configuration flinkConfig;
+
+	@Override
+	public void configure(Configuration config) {
+		flinkConfig = config;
```
Comment (Myasuka) [inline flink-filesystems/flink-azure-fs-hadoop/src/main/java/org/apache/flink/fs/azurefs/AbstractAzureFSFactory.java]: Why not use `hadoopConfig` to separate specific configurations of Azure just like other filesystem factory did?

File: flink-filesystems/flink-azure-fs-hadoop/src/main/java/org/apache/flink/fs/azurefs/AbstractAzureFSFactory.java (hunk 1 above)
Comment (piyushnarang) [reply flink-filesystems/flink-azure-fs-hadoop/src/main/java/org/apache/flink/fs/azurefs/AbstractAzureFSFactory.java]: agree, updated

File: flink-filesystems/flink-azure-fs-hadoop/src/test/java/org/apache/flink/fs/azurefs/AzureFileSystemBehaviorITCase.java (hunk 2 above)
Comment (piyushnarang) [reply flink-filesystems/flink-azure-fs-hadoop/src/test/java/org/apache/flink/fs/azurefs/AzureFileSystemBehaviorITCase.java]: updated

**Comment by piyushnarang** [comment]
@Myasuka - thanks for taking a look. Updated to add this to opt.xml and some docs as well. Let me know if you think I should expand / clarify the docs or add some documentation to a specific location apart from this.

File: flink-filesystems/flink-azure-fs-hadoop/src/main/java/org/apache/flink/fs/azurefs/AbstractAzureFSFactory.java (hunk 3 above)
Comment (piyushnarang) [reply flink-filesystems/flink-azure-fs-hadoop/src/main/java/org/apache/flink/fs/azurefs/AbstractAzureFSFactory.java]: I'm not sure I understand. The approach I've taken is basically copying relevant Flink config entries to the hadoop config in the `AzureFileSystem` class if they match a `azure.` or `fs.azure.` prefix. Were you suggesting I base this off the S3 fs factory? or a different fs factory? (seems like the various ones are a bit different from each other on this)

Comment (Myasuka) [reply flink-filesystems/flink-azure-fs-hadoop/src/main/java/org/apache/flink/fs/azurefs/AbstractAzureFSFactory.java]: hmm, previously I thought you did not take into the `hadoopConfig`, but then I found you just follow the `MapRFsFactory`'s way to instantiate the hadoop configuration when creating the file system instead of instantiating them within `FileSystemFactory#create(URI fsUri)` before creating the file system like other file factories did.
If this works fine, it would be okay to do so.

Comment (piyushnarang) [reply flink-filesystems/flink-azure-fs-hadoop/src/main/java/org/apache/flink/fs/azurefs/AbstractAzureFSFactory.java]: Yeah I was able to test this out and verify it works ok.

**Comment by piyushnarang** [comment]
@Myasuka - did you get a chance to take a look at the rework? Anything else to address or can we merge this?

**Comment by shuai-xu** [comment]
@piyushnarang Thanks for your contribution. I have tested your implementation. It can works. However, there are serval potential problems.
1. The ITcase needs the account to turn off the security option, or else the cases using http will fail. Could you try to check the security option automatically or else add some comments to notice it?
3. The flink-azure-fs-hadoop does not contain all jars it depends, so if user want to use it, they need to copy flink-azure-fs-hadoop.jar hadoop-azure.jar azure-storage.jar and jetty-util.jar to lib/ path.

**Comment by rmetzger** [comment]
@flinkbot approve description

File: flink-filesystems/flink-azure-fs-hadoop/pom.xml [hunk 4]
```diff
@@ -0,0 +1,80 @@
...
+		<!-- for the behavior test suite -->
+		<dependency>
+			<groupId>org.apache.flink</groupId>
+			<artifactId>flink-core</artifactId>
+			<version>${project.version}</version>
+			<scope>test</scope>
+			<type>test-jar</type>
+		</dependency>
+
+	</dependencies>
```
[the remark this answers is not in the document]
Comment (piyushnarang) [reply flink-filesystems/flink-azure-fs-hadoop/pom.xml]: sure will add. How do I go about adding the various notice / license files?

File: flink-filesystems/flink-azure-fs-hadoop/src/main/java/org/apache/flink/fs/azurefs/AzureFileSystem.java [hunk 5]
```diff
@@ -0,0 +1,77 @@
...
+	private static final Logger LOG = LoggerFactory.getLogger(AzureFileSystem.class);
+
+	private static final String[] CONFIG_PREFIXES = { "fs.azure.", "azure." };
+
+	public AzureFileSystem(URI fsUri, Configuration flinkConfig) throws IOException {
+		super(createInitializedAzureFS(fsUri, flinkConfig));
+	}
+
+	// uri is of the form: wasb(s)://yourcontainer@youraccount.blob.core.windows.net/testDir
+	private static org.apache.hadoop.fs.FileSystem createInitializedAzureFS(URI fsUri, Configuration flinkConfig) throws IOException {
```
[the remark this answers is not in the document]
Comment (piyushnarang) [reply flink-filesystems/flink-azure-fs-hadoop/src/main/java/org/apache/flink/fs/azurefs/AzureFileSystem.java]: sure, will update this. I'm thinking I might just do away with the AzureFileSystem class in that case. Have the factory create a HadoopFileSystem which is passed the NativeAzureFileSystem.

**Comment by piyushnarang** [comment]
Thanks for getting back and taking a look @tillrohrmann and @shuai-xu. To answer some of your top level comments / questions:
1) The flink-azure-fs-hadoop jars are written out to the opt/ directory in the flink-dist (based on comments in the original review). I've tested this in local flink jobs, I've trying to sort out some things to test this out on our internal hadoop cluster. 
2) I can add some E2E tests on the lines of `test_shaded_presto_s3`. Do we have an azure bucket at the project level that I should use? Or should I just add the tests similar to the IT test and the folks who run it can fill in their azure details?
3) ITCase with HTTP - Seems like they do support retrieving this information via their REST API (https://docs.microsoft.com/en-us/rest/api/storagerp/storageaccounts/getproperties). I can try and hook this up to the IT case to only run the HTTP tests if `supportsHttpsTrafficOnly` = false. 
4) Dependency jars - If I understand correctly, some of these dependent jars (like hadoop-azure / azure-storage) should be part of the hadoop install right? Or do I need to tweak things to package them?

File: flink-filesystems/flink-azure-fs-hadoop/pom.xml (hunk 4 above)
[the remark this answers is not in the document]
Comment (tillrohrmann) [reply flink-filesystems/flink-azure-fs-hadoop/pom.xml]: What we need to check is the license of the `hadoop-azure` dependency and all of its included transitive dependencies. We then need to add these to the `NOTICE` file of this module. Additionally, we need to add them to the `NOTICE-binary` file because the Azure FS will be included in the flink distribution I guess.

If you want, then I can help with this step, once the PR is ready to be merged.

**Comment by tillrohrmann** [comment]
Thanks for addressing our comments @piyushnarang.

2. We should do it similar to the IT test because we don't have an Azure bucket.
3. Sounds good to me.
4. Usually we build a fat jar for each file system to make the usage of it as easy as possible for the user. That way we don't require the user to add additional dependencies to its cluster deployment.

File: flink-filesystems/flink-azure-fs-hadoop/src/main/java/org/apache/flink/fs/azurefs/AzureFileSystem.java [hunk 6]
```diff
@@ -0,0 +1,77 @@
...
+		org.apache.hadoop.conf.Configuration hadoopConfig = HadoopUtils.getHadoopConfiguration(flinkConfig);
+
+		copyFlinkToHadoopConfig(flinkConfig, hadoopConfig);
```
[the remark this answers is not in the document]
Comment (piyushnarang) [reply flink-filesystems/flink-azure-fs-hadoop/src/main/java/org/apache/flink/fs/azurefs/AzureFileSystem.java]: hmm so I'm wondering if we could push this to a follow up change. The hadoop config loader is in the flink-s3-fs-base module. So we'll have to spin up a new module and refactor things a bit in the s3 code as well. Also if we want to do it correctly, we probably want to use the config loader for the other non-S3 filesystems (like OSS) which are also currently doing things in a similar fashion.

**Comment by piyushnarang** [comment]
@tillrohrmann do you know if there's any special setup required for the flink e2e tests to run on developer machines? I'm trying to run a azure_fs e2e test I've created and am consistently seeing the test failing due to a timeout as the dispatcher rest endpoint hasn't come up in 20s. I also see the same error when I try to run the test_batch_wordcount.sh:
```
$ export FLINK_DIR=flink-dist/target/flink-1.9-SNAPSHOT-bin/flink-1.9-SNAPSHOT
$ export HADOOP_CLASSPATH=...
$ export HADOOP_CONF_DIR=...
$ flink-end-to-end-tests/run-single-test.sh flink-end-to-end-tests/test-scripts/test_batch_wordcount.sh 
Starting cluster.
Starting standalonesession daemon on host C02T3863HF1R.
Starting taskexecutor daemon on host C02T3863HF1R.
Waiting for dispatcher REST endpoint to come up...
...
Dispatcher REST endpoint has not started within a timeout of 20 sec
[FAIL] Test script contains errors.
Checking for errors...
No errors in log files.
Checking for exceptions...
No exceptions in log files.
Checking for non-empty .out files...
Found non-empty .out files:
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/p.narang/workspace/flink/flink-dist/target/flink-1.9-SNAPSHOT-bin/flink-1.9-SNAPSHOT/lib/slf4j-log4j12-1.7.15.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/p.narang/Downloads/hadoop-2.7.7/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/p.narang/workspace/flink/flink-dist/target/flink-1.9-SNAPSHOT-bin/flink-1.9-SNAPSHOT/lib/slf4j-log4j12-1.7.15.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/p.narang/Downloads/hadoop-2.7.7/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]

[FAIL] 'flink-end-to-end-tests/test-scripts/test_batch_wordcount.sh' failed after 0 minutes and 26 seconds! Test exited with exit code 1 and the logs contained errors, exceptions or non-empty .out files
```

**Comment by piyushnarang** [comment]
P.S. @tillrohrmann / @shuai-xu - I was able to test this out on a hadoop cluster. I had to copy the following jars to my lib dir to get it to work - `azure-storage-2.0.0.jar`,  `flink-azure-fs-hadoop-1.6-SNAPSHOT.jar`,  `hadoop-azure-*.jar`
I'll dig into how the other filesystems are achieving this in their uber jar so that we can also generate one flink-azure-fs-hadoop jar which includes the azure-storage and hadoop-azure deps.

**Comment by piyushnarang** [comment]
Seems like the missing ingredient was this commit: https://github.com/apache/flink/pull/8117/commits/8205a210b748110944ac27a3590b995d0c942a42
This was missing when shuai tested and when I first built my 1.6 jars. 
Unfortunately though, I am running into some shading issues when I try to use it on my cluster so I'll dig into them over the coming days:
```
Caused by: java.lang.NoClassDefFoundError: org/apache/flink/fs/shaded/hadoop3/org/apache/hadoop/hdfs/HdfsConfiguration
	at org.apache.flink.fs.azurefs.AzureFileSystem.createInitializedAzureFS(AzureFileSystem.java:48)
...
```

File: flink-filesystems/flink-azure-fs-hadoop/pom.xml [hunk 7]
```diff
@@ -77,4 +77,53 @@ under the License.
...
+							<shadeTestJar>false</shadeTestJar>
+							<artifactSet>
+								<includes>
+									<include>*:*</include>
+								</includes>
+							</artifactSet>
+							<relocations>
+								<relocation>
+									<pattern>org.apache.hadoop</pattern>
+									<shadedPattern>org.apache.flink.fs.shaded.hadoop3.org.apache.hadoop</shadedPattern>
```
Comment (tillrohrmann) [inline flink-filesystems/flink-azure-fs-hadoop/pom.xml]: I guess it depends on `hadoop.version` whether it's `hadoop3` or not. Thus, I would simply remove `hadoop3` here.

File: flink-filesystems/flink-azure-fs-hadoop/src/main/java/org/apache/flink/fs/azurefs/AbstractAzureFSFactory.java [hunk 8]
```diff
@@ -48,6 +55,33 @@ public void configure(Configuration config) {
 	public FileSystem create(URI fsUri) throws IOException {
 		checkNotNull(fsUri, "passed file system URI object should not be null");
 		LOG.info("Trying to load and instantiate Azure File System");
-		return new AzureFileSystem(fsUri, flinkConfig);
+		return new HadoopFileSystem(createInitializedAzureFS(fsUri, flinkConfig));
+	}
+
+	// uri is of the form: wasb(s)://yourcontainer@youraccount.blob.core.windows.net/testDir
+	private org.apache.hadoop.fs.FileSystem createInitializedAzureFS(URI fsUri, Configuration flinkConfig) throws IOException {
+		org.apache.hadoop.conf.Configuration hadoopConfig = HadoopUtils.getHadoopConfiguration(flinkConfig);
```
Comment (tillrohrmann) [inline flink-filesystems/flink-azure-fs-hadoop/src/main/java/org/apache/flink/fs/azurefs/AbstractAzureFSFactory.java]: Can't we use the `HadoopConfigLoader` here? Then we would not have to do the manual copying step.

File: flink-filesystems/flink-azure-fs-hadoop/pom.xml [hunk 9]
```diff
@@ -65,7 +65,6 @@ under the License.
 			<groupId>org.apache.hadoop</groupId>
 			<artifactId>hadoop-hdfs</artifactId>
 			<version>${hadoop.version}</version>
-			<scope>test</scope>
```
Comment (tillrohrmann) [inline flink-filesystems/flink-azure-fs-hadoop/pom.xml]: Why did you remove the `test` scope here?

File: flink-filesystems/flink-azure-fs-hadoop/pom.xml (hunk 7 above)
Comment (piyushnarang) [reply flink-filesystems/flink-azure-fs-hadoop/pom.xml]: yeah agree, makes sense. Will update

File: flink-filesystems/flink-azure-fs-hadoop/src/main/java/org/apache/flink/fs/azurefs/AbstractAzureFSFactory.java (hunk 8 above)
Comment (piyushnarang) [reply flink-filesystems/flink-azure-fs-hadoop/src/main/java/org/apache/flink/fs/azurefs/AbstractAzureFSFactory.java]: Yeah I can use the HadoopConfigLoader. It is a slightly more involved change though as the config loader needs to be moved out of the s3-base module to a new one and we also have other file system factories doing similar copying which also need to be updated if we want to do things thoroughly. 
If you're keen on using it here as part of this PR, I could kick start it by creating a filesystem commons module, move the config loader there and use it in this factory. wdyt?

File: flink-filesystems/flink-azure-fs-hadoop/pom.xml (hunk 9 above)
Comment (piyushnarang) [reply flink-filesystems/flink-azure-fs-hadoop/pom.xml]: I was running into some issues when I included the shade plugin and tried to run this on the cluster / e2e tests:
```
Caused by: java.lang.NoClassDefFoundError: org/apache/flink/fs/shaded/hadoop3/org/apache/hadoop/hdfs/HdfsConfiguration
	at org.apache.flink.fs.azurefs.AzureFileSystem.createInitializedAzureFS(AzureFileSystem.java:48)
```

Comment (tillrohrmann) [reply flink-filesystems/flink-azure-fs-hadoop/pom.xml]: Thanks for the clarification.

File: flink-filesystems/flink-azure-fs-hadoop/src/main/java/org/apache/flink/fs/azurefs/AbstractAzureFSFactory.java (hunk 8 above)
Comment (tillrohrmann) [reply flink-filesystems/flink-azure-fs-hadoop/src/main/java/org/apache/flink/fs/azurefs/AbstractAzureFSFactory.java]: Looking at the details of the `HadoopConfigLoader` and the `HadoopUtils`, it actually makes a bigger difference than thought. `HadoopUtils` loads the Hadoop configuration from a set of specified locations (assuming that Hadoop is available). In contrast to that `HadoopConfigLoader` creates a vanilla `HadoopConfiguration` and populates it with the contents of the Flink configuration. So the `HadoopConfigLoader` is actually used in the S3 FileSystem implementations to completely encapsulate the Hadoop dependencies so that the S3 filesystem implementation is completely self-contained (see FLINK-10362). I think we should do the same for the Azure FS since it is not relevant for the user which implementation we use here (Hadoop) and one should also be able to use it without having Hadoop installed.

I would propose to move the `HadoopConfigLoader` to the `flink-hadoop-fs` module since all implementations which use a Hadoop based implementation will depend on this one. I think the only filesystem not doing it correctly at the moment is the `SwiftFileSystem`. Once we have moved the utility, we should create a JIRA issue to update this file system as a follow up.

Comment (piyushnarang) [reply flink-filesystems/flink-azure-fs-hadoop/src/main/java/org/apache/flink/fs/azurefs/AbstractAzureFSFactory.java]: Ok, sounds good. I'll take a stab at this and can create a follow up jira for the swiftfs.

Comment (piyushnarang) [reply flink-filesystems/flink-azure-fs-hadoop/src/main/java/org/apache/flink/fs/azurefs/AbstractAzureFSFactory.java]: Updated the review to incorporate this. I've filed: https://jira.apache.org/jira/browse/FLINK-12394

**Comment by tillrohrmann** [comment]
Thanks for updating the PR @piyushnarang. I think there is currently a compilation problem because of the moved `HadoopConfigLoader`.

```
15:20:57.850 [ERROR] /home/travis/build/apache/flink/flink-filesystems/flink-s3-fs-hadoop/src/main/java/org/apache/flink/fs/s3hadoop/S3FileSystemFactory.java:[24,37] package org.apache.flink.runtime.util does not exist
15:20:57.850 [ERROR] /home/travis/build/apache/flink/flink-filesystems/flink-s3-fs-hadoop/src/main/java/org/apache/flink/fs/s3hadoop/S3FileSystemFactory.java:[67,16] cannot find symbol
  symbol:   class HadoopConfigLoader
  location: class org.apache.flink.fs.s3hadoop.S3FileSystemFactory
15:20:57.851 [ERROR] /home/travis/build/apache/flink/flink-filesystems/flink-s3-fs-hadoop/src/main/java/org/apache/flink/fs/s3hadoop/S3FileSystemFactory.java:[68,28] cannot find symbol
  symbol:   class HadoopConfigLoader
  location: class org.apache.flink.fs.s3hadoop.S3FileSystemFactory
```

I think we need to update the `S3FileSystemFactory`.

**Comment by piyushnarang** [comment]
Yeah let me check. I kicked off a `mvn clean install -DskipTests` on my machine before submitting and that seems to have gone through ok. I'll try and repro what the travis build is doing and see if I can trigger the failure.

**Comment by piyushnarang** [comment]
Ok I think I didn't catch the issue as I was using mvn 3.5 and it seems that the shade plugin behaves a bit differently on it. When I build with 3.2.5 (what we default to in the project), I was able to trigger the failure. 
Seems to be due to the flink-s3-fs-base module filtering all the classes in the util package (where I had placed the HadoopConfigLoader). I'm not really sure on the context of the original change, I've updated to only filter the HadoopUtils class (no other classes in that package).

File: flink-filesystems/flink-azure-fs-hadoop/pom.xml [hunk 10]
```diff
@@ -0,0 +1,155 @@
...
+		<dependency>
+			<groupId>org.apache.flink</groupId>
+			<artifactId>flink-core</artifactId>
+			<version>${project.version}</version>
+			<scope>provided</scope>
+		</dependency>
+
+		<dependency>
+			<groupId>org.apache.flink</groupId>
+			<artifactId>flink-hadoop-fs</artifactId>
```
Comment (tillrohrmann) [inline flink-filesystems/flink-azure-fs-hadoop/pom.xml]: Since we want to make the Azure FS self contained, let's use the `flink-fs-hadoop-shaded` dependency instead of `flink-hadoop-fs`.

File: flink-filesystems/flink-azure-fs-hadoop/pom.xml [hunk 11]
```diff
@@ -0,0 +1,155 @@
...
+			<groupId>org.apache.hadoop</groupId>
+			<artifactId>hadoop-azure</artifactId>
+			<version>${fs.azure.version}</version>
+		</dependency>
+
+		<!-- for the Azure HDFS related tests -->
+		<dependency>
+			<groupId>org.apache.hadoop</groupId>
+			<artifactId>hadoop-hdfs</artifactId>
+			<version>${hadoop.version}</version>
```
Comment (tillrohrmann) [inline flink-filesystems/flink-azure-fs-hadoop/pom.xml]: If we use `flink-fs-hadoop-shaded`, then we need to set this value to `${fs.hadoopshaded.version}`

File: flink-filesystems/flink-hadoop-fs/src/main/java/org/apache/flink/runtime/util/HadoopConfigLoader.java [hunk 12]
```diff
@@ -16,7 +16,7 @@
  * limitations under the License.
  */
 
-package org.apache.flink.fs.s3.common;
+package org.apache.flink.runtime.util;
```
Comment (tillrohrmann) [inline flink-filesystems/flink-hadoop-fs/src/main/java/org/apache/flink/runtime/util/HadoopConfigLoader.java]: I'm wondering whether we shouldn't put the `HadoopConfigLoader` into the `flink-fs-hadoop-shaded` module, because it is intended for self-contained fs implementations which don't read a HDFS/Yarn configuration from disk but simply instantiate the `Configuration` contained in this module.

File: flink-filesystems/flink-s3-fs-base/pom.xml [hunk 13]
```diff
@@ -161,12 +161,17 @@ under the License.
 									<pattern>org.apache.flink.runtime.fs.hdfs</pattern>
 									<shadedPattern>org.apache.flink.fs.s3.common.hadoop</shadedPattern>
 								</relocation>
+								<!-- shade Flink's Hadoop FS utility classes -->
+								<relocation>
+									<pattern>org.apache.flink.runtime.util</pattern>
+									<shadedPattern>org.apache.flink.fs.s3.common</shadedPattern>
+								</relocation>
```
Comment (tillrohrmann) [inline flink-filesystems/flink-s3-fs-base/pom.xml]: I think we don't need to do these changes if we put `HadoopConfigLoader` into the `flink-fs-hadood-shaded` module.

File: flink-filesystems/flink-s3-fs-base/pom.xml [hunk 14]
```diff
@@ -161,12 +161,17 @@ under the License.
 									<pattern>org.apache.flink.runtime.fs.hdfs</pattern>
```
Comment (tillrohrmann) [inline flink-filesystems/flink-s3-fs-base/pom.xml]: Maybe we could place `util` under `fs` and then relocate `o.a.f.runtime.fs`. This would save us the second relocation pattern.

File: flink-filesystems/flink-azure-fs-hadoop/pom.xml [hunk 15]
```diff
@@ -0,0 +1,155 @@
...
+							<shadeTestJar>false</shadeTestJar>
+							<artifactSet>
+								<includes>
+									<include>*:*</include>
+								</includes>
+							</artifactSet>
+							<relocations>
+								<relocation>
+									<pattern>org.apache.hadoop</pattern>
+									<shadedPattern>org.apache.flink.fs.shaded.hadoop.org.apache.hadoop</shadedPattern>
```
Comment (tillrohrmann) [inline flink-filesystems/flink-azure-fs-hadoop/pom.xml]: If we add `flink-fs-hadoop-shaded,` then we can change the pattern back to `hadoop3`

File: flink-filesystems/flink-azure-fs-hadoop/pom.xml (hunk 11 above)
Comment (tillrohrmann) [reply flink-filesystems/flink-azure-fs-hadoop/pom.xml]: Sorry for asking again, but for what exactly do we need the `hadoop-hdfs` dependency?

File: flink-filesystems/flink-azure-fs-hadoop/pom.xml [hunk 16]
```diff
@@ -0,0 +1,155 @@
...
+		<dependency>
+			<groupId>org.apache.flink</groupId>
+			<artifactId>flink-hadoop-fs</artifactId>
+			<version>${project.version}</version>
+		</dependency>
+
+		<dependency>
+			<groupId>org.apache.hadoop</groupId>
+			<artifactId>hadoop-azure</artifactId>
+			<version>${fs.azure.version}</version>
```
Comment (tillrohrmann) [inline flink-filesystems/flink-azure-fs-hadoop/pom.xml]: If we use `flink-fs-hadoop-shaded` as Hadoop dependency, then we should set the version to `${fs.hadoopshaded.version}` and add an exclusion for `org.apache.hadoop:hadoop-common`.

**Comment by piyushnarang** [comment]
@tillrohrmann - I'm not really sure I understand why we need the flink-hadoop-fs-shaded module. Is the whole point of that to reduce the size of the flink-azure-fs jar? Or something else? Moreover, is it essential to add that right now? We've iterated a fair bit on this PR already and if there is something that can be addressed in a future review, I'd prefer doing that rather than trying to tackle everything in this one.

**Comment by piyushnarang** [comment]
Thanks @tillrohrmann. I'm happy to put in a follow up on the shading stuff. Can sit down with that next week and put in a fresh PR on that.

**Comment by tillrohrmann** [comment]
Thanks @piyushnarang. I'll take a stab at the LICENSE and NOTICE file.

**Comment by piyushnarang** [comment]
@tillrohrmann - did you get a chance to take a stab at this?

**Comment by tillrohrmann** [comment]
I'm still on it. Sorry for the slow progress @piyushnarang.
