### PR TITLE
[FLINK-9697] Provide connector for modern Kafka

### PR DESCRIPTION
**Pull request by yanghua**
## What is the purpose of the change

*This pull request provides connector for Kafka 2.0.0*

## Brief change log

  - *Provide connector for Kafka 2.0.0*

## Verifying this change

This change is already covered by existing tests*.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (**yes** / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (**yes** / no)
  - If yes, how is the feature documented? (not applicable / docs / **JavaDocs** / not documented)

### CODE REVIEW

**Comment by yanghua** [comment]
Currently this PR is not ready to be reviewed, it still needs some refactoring.

**Comment by pnowojski** [comment]
@yanghua CC me and/or request review when this will be ready to review

**Comment by yanghua** [comment]
@pnowojski OK. There is a test case `testOneToOneAtLeastOnceRegularSink` always can not been passed, I am trying to find the reason.

**Comment by pnowojski** [comment]
In existing `Kafka011ProducerExactlyOnceITCase`, at least once tests are not passing. Please check the comment in `Kafka011ProducerExactlyOnceITCase#testOneToOneAtLeastOnceRegularSink` for more details. It might be the same issue.

**Comment by yanghua** [comment]
I have already read the comment for this method, yes, it will cause the test program to become unresponsive. But each PR will verify this test, why it passed very many times, but this PR, I committed twice, it failed on this use case. Therefore, I suspect that it is caused by the kafka 2.0 version. But with your reminder, it looks like it's a probabilistic problem, and it can fail in existing code.

**Comment by yanghua** [comment]
@pnowojski If we don't consider the failed test case, then this PR applies to both Kafka client 1.0 and kafka client 2.0. Basically it also applies to kafka 0.11 (except for a reflection field of the producer transaction and the associated test code). So, I want to hear your opinion. Should we build a connector that fits the three versions of kafka client next?

**Comment by yanghua** [comment]
OK, @aljoscha This PR currently mainly proves that most of the source code of flink-connector-kafka-0.11 is compatible with kafka client 2.0 (regardless of the test cases that inherently have a risk of failure). Then, next, I will refactor it so that it does not depend on flink-connector-kafka-0.11.

**Comment by aljoscha** [comment]
Excellent 👌

**Comment by pnowojski** [comment]
@yanghua I would assume that deadlocking/becoming unresponsive just proves that our `at-least-once` test is broken and should be replaced. Feel free to disable it for your `2.0.0` version.

Keep in mind that the idea is to use our 2.0 connector, to talk to all Kafka versions from 0.11+. That requires some additional testing and refactoring of our existing testing code base. So far we were testing `flink-connector-kafka-0.11` against only a single kafka version (`0.11`). Now, we might need to test our `flink-connector-kafka-2.0` against Kafka `0.11`, `1.0`, `1.1` and `2.0`.

**Comment by yanghua** [comment]
@pnowojski Ok, what I am currently doing is removing the cascading dependencies in flink-connector-kafka-2.0. And verify the correctness of this step.

**Comment by aljoscha** [comment]
Excellent! 👌 

I'm currently working on adding support for Scala 2.12, and this PR is a prerequisite for that, since it makes it easier to remove older Kafka connectors from the Scala 2.12 build. The reason for this is that there are no Scala 2.12 dependencies for Kafka version < 0.10.2.x

**Comment by yanghua** [comment]
@alexeyt820 thanks for paying attention to this PR. I am trying to fix some test issue. Based on the community's efficiency, It may not catch up with the time point of releasing 1.7. I will try my best to fix these test issues as soon as possible.

File: flink-connectors/flink-connector-kafka-2.0/pom.xml [hunk 1]
```diff
@@ -0,0 +1,312 @@
...
+	<modelVersion>4.0.0</modelVersion>
+
+	<parent>
+		<artifactId>flink-connectors</artifactId>
+		<groupId>org.apache.flink</groupId>
+		<version>1.7-SNAPSHOT</version>
+		<relativePath>..</relativePath>
+	</parent>
+
+	<artifactId>flink-connector-kafka-2.0</artifactId>
```
[the remark this answers is not in the document]
Comment (aljoscha) [reply flink-connectors/flink-connector-kafka-2.0/pom.xml]: Agreed, but we still have to add the Scala suffix, i.e. it should be `flink-connector-kafka_${scala.binary.version}` because we depend on `flink-streaming`.

**Comment by aljoscha** [comment]
@yanghua What is the problem with the failing tests? Do you have any idea so far?

**Comment by yanghua** [comment]
@aljoscha some test cases which used kafka-server, failed with this exception : 

```
java.lang.NoClassDefFoundError: org/slf4j/event/Level

	at kafka.utils.CoreUtils$.swallow$default$3(CoreUtils.scala:84)
	at kafka.server.KafkaServer.shutdown(KafkaServer.scala:566)
	at org.apache.flink.streaming.connectors.kafka.KafkaTestEnvironmentImpl.shutdown(KafkaTestEnvironmentImpl.java:314)
	at org.apache.flink.streaming.connectors.kafka.KafkaTestBase.shutdownClusters(KafkaTestBase.java:174)
	at org.apache.flink.streaming.connectors.kafka.KafkaTestBase.shutDownServices(KafkaTestBase.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

But I checked, the `slf4j-api` exists in the dependencies.

File: flink-connectors/flink-connector-kafka-2.0/pom.xml [hunk 2]
```diff
@@ -0,0 +1,312 @@
...
+		<dependency>
+			<groupId>org.apache.flink</groupId>
+			<artifactId>flink-table_${scala.binary.version}</artifactId>
+			<version>${project.version}</version>
+			<scope>provided</scope>
+			<!-- Projects depending on this project, won't depend on flink-table. -->
+			<optional>true</optional>
+		</dependency>
+
+		<dependency>
```
Comment (aljoscha) [inline flink-connectors/flink-connector-kafka-2.0/pom.xml]: @twalthr We don't need the Avro and Json dependencies here anymore, right?

**Comment by aljoscha** [comment]
Ignoring the `slf4j` error for now, I see some other errors, for example that `kafka.consumer.ConsumerConfig` cannot be found. The problem is that the packages starting with `kafka.*` are deprecated and have been removed in Kafka 2.0.0. (see here: https://github.com/apache/kafka/blob/1.0/core/src/main/scala/kafka/consumer/ConsumerConfig.scala#L26) I think the first step is removing all of those dependencies from the connector-base package. Or, if that is not possible, it might be that Kafka 2.0 can't use the connector-base package.

**Comment by aljoscha** [comment]
We seem to be using those classes in packages that are not there anymore:
```
~/D/f/f/flink-connector-kafka-base (finish-pr-6703-kafka-20|✔) $ rg "import kafka\."
src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaTestEnvironment.java
30:import kafka.server.KafkaServer;

src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaConsumerTestBase.java
81:import kafka.consumer.Consumer;
82:import kafka.consumer.ConsumerConfig;
83:import kafka.consumer.ConsumerIterator;
84:import kafka.consumer.KafkaStream;
85:import kafka.javaapi.consumer.ConsumerConnector;
86:import kafka.message.MessageAndMetadata;
87:import kafka.server.KafkaServer;
```

File: flink-connectors/flink-connector-kafka-2.0/pom.xml (hunk 1 above)
[the remark this answers is not in the document]
Comment (yanghua) [reply flink-connectors/flink-connector-kafka-2.0/pom.xml]: OK, will rename it.

File: flink-connectors/flink-connector-kafka-2.0/src/main/java/org/apache/flink/streaming/connectors/kafka/FlinkKafka20ErrorCode.java [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+
+package org.apache.flink.streaming.connectors.kafka;
+
+import org.apache.flink.annotation.PublicEvolving;
+
+/**
+ * Error codes used in {@link FlinkKafka20Exception}.
+ */
+@PublicEvolving
+public enum FlinkKafka20ErrorCode {
```
[the remark this answers is not in the document]
Comment (yanghua) [reply flink-connectors/flink-connector-kafka-2.0/src/main/java/org/apache/flink/streaming/connectors/kafka/FlinkKafka20ErrorCode.java]: Will rename them.

**Comment by aljoscha** [comment]
Yes, the reason (as I said) is that 1.0 still has the code in those `kafka.consumer...` packages while in 2.0 they are removed.

**Comment by aljoscha** [comment]
@yanghua Actually, I think you can make it work by just removing method `readTopicToList` from `KafkaConsumerTestBase` and and by removing the `kafka.consumer....` imports.

**Comment by yanghua** [comment]
@aljoscha yes, you are right, I have update the PR.

**Comment by yanghua** [comment]
@aljoscha still many failed test cases because of timeout and ClassNotFound.

**Comment by aljoscha** [comment]
@yanghua According to the slf4j doc `Level` is only available since version `1.7.15` while Flink uses `1.7.7`: https://www.slf4j.org/api/org/slf4j/event/Level.html. Could you try updating to `1.7.15`?

**Comment by aljoscha** [comment]
Now the tests only fail on timeouts.

**Comment by yanghua** [comment]
yes, thanks for your solution @aljoscha . I will take a look about the failed test case because of timeout.

**Comment by aljoscha** [comment]
it seems the tests pass now 👍 

Please make sure to also:
 - rename the module to `flink-connector-kafka_${scala.binary.version}`
 - remove the `20` part from the classes
 - remove some unrelated leftover changes in the 0.11 connector

**Comment by yanghua** [comment]
@aljoscha Yes, the test passed. I will change the module name later, but there is a little doubt. If no version number is added, the user uses the connector and introduces a very early kafka dependency (eg, 0.8, 0.9). Currently, for lower kafka dependencies, this connector should not be able to provide support. For this situation, should we prevent it from happening?

**Comment by aljoscha** [comment]
We can prevent it if it's easily possible but we can also rely on documentation for that, in my opinion.

**Comment by yanghua** [comment]
@aljoscha when I rename 'Kafka20TableSink' -> 'KafkaTableSink', but 'KafkaTableSink' exists in 'flink-connector-kafka-base'. Shall we rename 'KafkaTableSink' to 'KafkaTableSinkBase'?

**Comment by aljoscha** [comment]
> @aljoscha when I rename 'Kafka20TableSink' -> 'KafkaTableSink', but 'KafkaTableSink' exists in 'flink-connector-kafka-base'. Shall we rename 'KafkaTableSink' to 'KafkaTableSinkBase'?

Yes, I think that's the right approach! 👍

File: flink-connectors/flink-connector-kafka-2.0/pom.xml [hunk 4]
```diff
@@ -0,0 +1,318 @@
...
+											<artifact>*:*</artifact>
+											<excludes>
+												<exclude>kafka/kafka-version.properties</exclude>
+											</excludes>
+										</filter>
+									</filters>
+									<relocations>
+										<relocation>
+											<pattern>org.apache.kafka</pattern>
+											<shadedPattern>org.apache.flink.kafka10.shaded.org.apache.kafka</shadedPattern>
```
Comment (aljoscha) [inline flink-connectors/flink-connector-kafka-2.0/pom.xml]: this needs to be changed to something like `org.apache.flink.kafka.shaded.org.apache.kafka` or if that's not possible `org.apache.flink.newkafka.shaded.org.apache.kafka`

File: flink-connectors/flink-connector-kafka-base/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaProducerTestBase.java [hunk 5]
```diff
@@ -204,15 +204,15 @@ public void cancel() {
 	 */
 	@Test
 	public void testOneToOneAtLeastOnceRegularSink() throws Exception {
-		testOneToOneAtLeastOnce(true);
+		//testOneToOneAtLeastOnce(true);
```
Comment (aljoscha) [inline flink-connectors/flink-connector-kafka-base/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaProducerTestBase.java]: These tests are still disabled.

Comment (yanghua) [reply flink-connectors/flink-connector-kafka-base/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaProducerTestBase.java]: You mean make them enable?

File: flink-connectors/flink-connector-kafka-2.0/src/main/java/org/apache/flink/streaming/connectors/kafka/internal/metrics/KafkaMetricMuttableWrapper.java [hunk 6]
```diff
@@ -0,0 +1,45 @@
...
+import org.apache.flink.annotation.Internal;
+import org.apache.flink.metrics.Gauge;
+
+import org.apache.kafka.common.Metric;
+
+/**
+ * Gauge for getting the current value of a Kafka metric.
+ */
+@Internal
+public class KafkaMetricMuttableWrapper implements Gauge<Double> {
```
[the remark this answers is not in the document]
Comment (aljoscha) [reply flink-connectors/flink-connector-kafka-2.0/src/main/java/org/apache/flink/streaming/connectors/kafka/internal/metrics/KafkaMetricMuttableWrapper.java]: I see. I know it's a copy from the original code but there's a typo in there: it should be `KafkaMetricMutableWrapper`.

**Comment by aljoscha** [comment]
Could you please also mark the consumer and producer as `@PublicEvolving`?

**Comment by aljoscha** [comment]
And we could probably add the Javadoc from `FlinkKafkaConsumer011` to the new Consumer as well.

**Comment by yanghua** [comment]
> Could you please also mark the consumer and producer as `@PublicEvolving`?

> And we could probably add the Javadoc from `FlinkKafkaConsumer011` to the new Consumer as well.

OK.

**Comment by yanghua** [comment]
@aljoscha compile and test successfully, what I should do next?

**Comment by aljoscha** [comment]
@yanghua Thanks for iterating on this so quickly! I will do a last thorough review next week and then hopefully merge.

To make the reviewing easier you could restructure the commits a bit. All prerequisite work should go into isolated commits and then the last commit should only have the new files for the Kafka 2.0 connector. For example the dependency change would be separate, or renaming the `KafkaTableSource` to `KafkaTableSourceBase` can be separate to more clearly see what each change does. This makes it way easier in the feature when someone looks at the changes and tries to figure out what was going on.

**Comment by yanghua** [comment]
@aljoscha OK, I will refactor the commits and commit messages.

**Comment by yanghua** [comment]
@aljoscha I have refactored and separated the commits.

File: flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/internal/KafkaConsumerCallBridge.java [hunk 7]
```diff
@@ -0,0 +1,48 @@
...
+import java.util.Collections;
+import java.util.List;
+
+/**
+ * The ConsumerCallBridge simply calls the {@link KafkaConsumer#assign(java.util.Collection)} method.
+ *
+ * <p>Because of that, we need two versions whose compiled code goes against different method signatures.
+ */
+@Internal
+public class KafkaConsumerCallBridge {
```
Comment (eliaslevy) [inline flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/internal/KafkaConsumerCallBridge.java]: Is the call bridge still needed in the new connector?  The connector has isn't own `KafkaConsumerThread` that does not need to handle multiple versions.

File: flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/internal/KafkaConsumerThread.java [hunk 8]
```diff
@@ -0,0 +1,525 @@
...
+	private final AtomicReference<Tuple2<Map<TopicPartition, OffsetAndMetadata>, KafkaCommitCallback>> nextOffsetsToCommit;
+
+	/** The configuration for the Kafka consumer. */
+	private final Properties kafkaProperties;
+
+	/** The queue of unassigned partitions that we need to assign to the Kafka consumer. */
+	private final ClosableBlockingQueue<KafkaTopicPartitionState<TopicPartition>> unassignedPartitionsQueue;
+
+	/** The indirections on KafkaConsumer methods, for cases where KafkaConsumer compatibility is broken. */
+	private final KafkaConsumerCallBridge consumerCallBridge;
```
Comment (eliaslevy) [inline flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/internal/KafkaConsumerThread.java]: Seems like this should not be needed anymore.

File: flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/internal/KafkaFetcher.java [hunk 9]
```diff
@@ -0,0 +1,238 @@
...
+		ConsumerRecord<?, ?> consumerRecord) throws Exception {
+
+		emitRecordWithTimestamp(record, partition, offset, consumerRecord.timestamp());
+	}
+
+	/**
+	 * Gets the name of this fetcher, for thread naming and logging purposes.
+	 */
+	protected String getFetcherName() {
+		return "Kafka 2.0 Fetcher";
```
Comment (eliaslevy) [inline flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/internal/KafkaFetcher.java]: Probably don't want to be updating this version every time there is a new Kafka release.

Comment (yanghua) [reply flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/internal/KafkaFetcher.java]: Can we give it a unified name? What about `Kafka Fetcher`?

File: flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/internal/KafkaConsumerCallBridge.java (hunk 7 above)
Comment (yanghua) [reply flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/internal/KafkaConsumerCallBridge.java]: You are right, I will try to remove it.

File: flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/FlinkKafkaConsumer.java [hunk 10]
```diff
@@ -0,0 +1,321 @@
...
+import java.util.Properties;
+import java.util.regex.Pattern;
+
+import static org.apache.flink.util.Preconditions.checkNotNull;
+import static org.apache.flink.util.PropertiesUtil.getBoolean;
+import static org.apache.flink.util.PropertiesUtil.getLong;
+
+/**
+ * The Flink Kafka Consumer is a streaming data source that pulls a parallel data stream from
+ * Apache Kafka 2.x. The consumer can run in multiple parallel instances, each of which will pull
```
[the remark this answers is not in the document]
Comment (yanghua) [reply flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/FlinkKafkaConsumer.java]: Will remove all.

File: flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/FlinkKafkaConsumer.java [hunk 11]
```diff
@@ -0,0 +1,321 @@
...
+ * (Note: These guarantees naturally assume that Kafka itself does not loose any data.)</p>
+ *
+ * <p>Please note that Flink snapshots the offsets internally as part of its distributed checkpoints. The offsets
+ * committed to Kafka / ZooKeeper are only to bring the outside view of progress in sync with Flink's view
+ * of the progress. That way, monitoring and other jobs can get a view of how far the Flink Kafka consumer
+ * has consumed a topic.</p>
+ *
+ * <p>Please refer to Kafka's documentation for the available configuration properties:
+ * http://kafka.apache.org/documentation.html#newconsumerconfigs</p>
+ */
```
[the remark this answers is not in the document]
Comment (yanghua) [reply flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/FlinkKafkaConsumer.java]: @eliaslevy I just clicked the URL in the comments and found it is validated. And the URL should provide configuration information. But the URL you provided is about consumer API. What do you think?

File: flink-connectors/flink-connector-kafka-base/src/main/java/org/apache/flink/table/descriptors/KafkaValidator.java [hunk 12]
```diff
@@ -36,6 +36,7 @@
 	public static final String CONNECTOR_VERSION_VALUE_09 = "0.9";
 	public static final String CONNECTOR_VERSION_VALUE_010 = "0.10";
 	public static final String CONNECTOR_VERSION_VALUE_011 = "0.11";
+	public static final String CONNECTOR_VERSION_VALUE_20 = "2.0";
```
Comment (yanghua) [inline flink-connectors/flink-connector-kafka-base/src/main/java/org/apache/flink/table/descriptors/KafkaValidator.java]: There is only residual information about kafka 2.0 here.

File: flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/FlinkKafkaConsumer.java (hunk 11 above)
[the remark this answers is not in the document]
Comment (eliaslevy) [reply flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/FlinkKafkaConsumer.java]: Apologies.  I misread it.  It is correct as it is.

File: flink-connectors/flink-connector-kafka-base/src/main/java/org/apache/flink/table/descriptors/KafkaValidator.java (hunk 12 above)
Comment (yanghua) [reply flink-connectors/flink-connector-kafka-base/src/main/java/org/apache/flink/table/descriptors/KafkaValidator.java]: @aljoscha It's here. The kafka version will be verified in KafkaValidator#validateVersion. I recommend removing the validation method and refactoring this constant as:

```java
public static final String CONNECTOR_UNTRACKED_VERSION_VALUE = "untracked"
```

What do you think?

**Comment by yanghua** [comment]
> Can deserializer access ConsumerRecord to get headers and timestamp? Or it will be PR on top this PR?

@alexeyt820 I agree with @aljoscha  that we should not add more changes to this PR so that its review progress is further delayed (because it is already large enough). We are trying to get it to catch up with the release point of Flink 1.7. Of course, the issue you mentioned is also valuable. I feel that once this PR is merged, we can immediately put the issue on the agenda. Thanks.

File: flink-connectors/flink-connector-kafka-base/src/main/java/org/apache/flink/table/descriptors/KafkaValidator.java (hunk 12 above)
Comment (aljoscha) [reply flink-connectors/flink-connector-kafka-base/src/main/java/org/apache/flink/table/descriptors/KafkaValidator.java]: I think it's okay to leave it in for now because I don't want to mess with how the table API source/sink validation works for now.

Comment (yanghua) [reply flink-connectors/flink-connector-kafka-base/src/main/java/org/apache/flink/table/descriptors/KafkaValidator.java]: OK, agree.

**Comment by aljoscha** [comment]
Thanks, @tzulitai!

@eliaslevy Are you happy with the state of the PR or is there anything else that needs changing?

@yanghua I'd like to make some changes while merging, if that's ok for you:

- rename `FlinkKafkaInnerProducer` to `FlinkKafkaInternalProducer`
- rename `KafkaMetricMuttableWrapper` to `KafkaMetricMutableWrapper`

**Comment by aljoscha** [comment]
As a follow-up, we should change/or add end-to-end tests that use the new Kafka consumer. We also need to do this for Scala 2.12 support because the existing connector hierarchy doesn't work with Scala 2.12.

**Comment by yanghua** [comment]
@aljoscha The renaming work has been completed.

> As a follow-up, we should change/or add end-to-end tests that use the new Kafka consumer. We also need to do this for Scala 2.12 support because the existing connector hierarchy doesn't work with Scala 2.12.

Will the tasks you refer to be completed on this PR, or after it is merged?

**Comment by yanghua** [comment]
In addition, I think we should modify the title of the JIRA issue and this PR. What do you think?

**Comment by aljoscha** [comment]
> @aljoscha The renaming work has been completed.
> 
> > As a follow-up, we should change/or add end-to-end tests that use the new Kafka consumer. We also need to do this for Scala 2.12 support because the existing connector hierarchy doesn't work with Scala 2.12.
> 
> Will the tasks you refer to be completed on this PR, or after it is merged?

I think after merging this PR, to unblock other things.

**Comment by aljoscha** [comment]
@yanghua I renamed the issue. You can also prefix all the commit titles with `[FLINK-9697]`.

**Comment by yanghua** [comment]
Refactored commit message and rebased this PR.

**Comment by eliaslevy** [comment]
@yanghua LGTM 👍

**Comment by aljoscha** [comment]
```
14:37:26.192 [ERROR] /home/travis/build/apache/flink/flink-connectors/flink-connector-kafka-0.11/src/main/java/org/apache/flink/streaming/connectors/kafka/internal/metrics/KafkaMetricMuttableWrapper.java:[30,8] class KafkaMetricMutableWrapper is public, should be declared in a file named KafkaMetricMutableWrapper.java
```

**Comment by yanghua** [comment]
cc @aljoscha

**Comment by yanghua** [comment]
Is there anything else I need to do about this PR?

**Comment by aljoscha** [comment]
@yanghua You don't have to do anything more, I'll merge shortly.

**Comment by aljoscha** [comment]
@alexeyt820 are you working on header and timestamp access to get it rebased and working on top of this?

**Comment by yanghua** [comment]
Maybe we can create an umbrella issue on JIRA to track the unfinished work around this PR. After it will be merged, I am also happy to continue with some remaining issues.

**Comment by aljoscha** [comment]
Thanks a lot for iterating on this and coming up with a good solution in the end, @yanghua!

And also thanks a lot to @eliaslevy for the initial suggestion and for helpful reviews!

@yanghua As a follow-up, do you want to update the documentation as well? Plus, we can add an end-to-end test for this.

**Comment by aljoscha** [comment]
I merged manually to master.

**Comment by yanghua** [comment]
@aljoscha Yes, I am happy to follow up on the documentation and strengthen the testing of it. Considering that 1.7 is released soon, I still have a lot of important PR hopes to catch up with the release point, so maybe I will follow those PRs before the 1.7 branch is cut off.

**Comment by zentol** [comment]
@aljoscha @yanghua Did we just merge another kafka connector that takes more than 10 minutes to test?

**Comment by yanghua** [comment]
@zentol I did increase the timeout for some tests, because in the new kafka client, the default timeout for some APIs (the API for getting partition information) is equal to the timeout (60s) we originally set for the test case, so I increased the test case's timeout to 120s to prevent the test case from throwing a timeout exception.

**Comment by alexeyt820** [comment]
@aljoscha, I can work on header and timestamp access this week. I think that we still need to wrap ConsumerRecord, because seems KeyedDeserializationSchema is used by legacy connectors as well.

**Comment by yanghua** [comment]
@alexeyt820 @aljoscha Do you agree I create an umbrella issue for the modern kafka connector?

**Comment by alexeyt820** [comment]
Fine with me

**Comment by yanghua** [comment]
@aljoscha I have create an umbrella issue ([FLINK-10598](https://issues.apache.org/jira/browse/FLINK-10598)) to track the issues about the modern kafka connector.

@alexeyt820 I do not know if the issue about "header and timestamp" that you are processing has been created on JIRA or not, if yes, you can archive it to FLINK-10598, if not, you can create a subtask for it. Thanks.

**Comment by alexeyt820** [comment]
@yanghua, FLINK-8354 (headers) and FLINK-8500 (timestamp), but seems I don't have permissions to change anything in these Jira issues

**Comment by yanghua** [comment]
@alexeyt820 I have moved these two issues into FLINK-10598 as a sub issue.

**Comment by pnowojski** [comment]
@yanghua is this new `flink-connector-kafka` module being compiled/tested on travis? I do not see the logs in travis builds and `flink-connector-kafka` is missing from `MODULES_CONNECTORS` defined in `tools/travis/stage.sh`.

**Comment by yanghua** [comment]
hi @pnowojski see [here](https://github.com/apache/flink/pull/6890#issuecomment-431917344).

**Comment by pnowojski** [comment]
ok thx, we will have to clean this up somehow.

**Comment by yanghua** [comment]
@pnowojski Yes, I have created [FLINK-10701](https://issues.apache.org/jira/browse/FLINK-10701) to track this problem.

**Comment by pnowojski** [comment]
One more issue question. Why the new connector has this exclussion:
```
		<dependency>
			<groupId>org.apache.flink</groupId>
			<artifactId>flink-connector-kafka-base_${scala.binary.version}</artifactId>
			<version>${project.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.apache.kafka</groupId>
					<artifactId>kafka_${scala.binary.version}</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```
Shouldn't the `flink-connector-kafka-base` be Kafka independent?

**Comment by yanghua** [comment]
@pnowojski Not only the modern kafka connector, but also other connectors. Each version of the flink-connector relies on the base module, while the base module shows dependencies on kafka. So, here we need to exclude it from the base module and explicitly introduce the high version dependency of kafka.

**Comment by pnowojski** [comment]
Yes I know about this issue with our connectors for kafka `[0.9, 0.11]`, but I had an impression that it was supposed to be fixed for the new one.

**Comment by yanghua** [comment]
The base module does not currently remove the dependency on kafka. We seem to have discussed it when implementing the kafka 1.0 version of the connector. However, it is not completed on this PR. Maybe I can refactor it? @pnowojski Do you agree?

**Comment by pnowojski** [comment]
Let's not do it know, but at some point of time we probably should do it. Unless we drop all of the connectors except of 2.0 - but in that case problem can reoccur once new Kafka version introduce some feature that we will want to use.
