### PR TITLE
[FLINK-3909] update Maven Failsafe version

### PR DESCRIPTION
**Pull request by mxm**
Failures during execution of the integration tests with the Maven
Failsafe plugin were silently ignored on Travis with Maven version
3.2.5. The problem is that failures are not passed on correctly from the
'integration-test' phase (where failures are recorded and tolerated) to
the 'verify' phase.

The cause of the error is most likely SUREFIRE-1127. An exception in the
'integration-test' is sometimes not flushed back to disk where it is
evaluated in the 'verify' phase. Bumping the version of the Failsafe
plugin from 2.18.1 to 2.19.1 fixes the issue.

Tests will fail for this PR ;)

### CODE REVIEW

**Comment by mxm** [comment]
Tests fail in flink-runtime now. Seem to be class path related problems.
```
  CheckpointIDCounterTest$ZooKeeperCheckpointIDCounterITCase.org.apache.flink.runtime.checkpoint.CheckpointIDCounterTest$ZooKeeperCheckpointIDCounterITCase Â» NoClassDefFound
  CheckpointIDCounterTest$ZooKeeperCheckpointIDCounterITCase.<clinit>:53 Â» NoSuchMethod
  CheckpointIDCounterTest$ZooKeeperCheckpointIDCounterITCase.testSerialIncrementAndGet Â» NoClassDefFound
  CheckpointIDCounterTest$ZooKeeperCheckpointIDCounterITCase.testSetCount Â» NoClassDefFound
  ZooKeeperCompletedCheckpointStoreITCase.org.apache.flink.runtime.checkpoint.ZooKeeperCompletedCheckpointStoreITCase Â» NoClassDefFound
  ZooKeeperCompletedCheckpointStoreITCase.testAddAndGetLatestCheckpoint Â» NoClassDefFound
  ZooKeeperCompletedCheckpointStoreITCase.testAddCheckpointMoreThanMaxRetained Â» NoClassDefFound
  ZooKeeperCompletedCheckpointStoreITCase.testDiscardAllCheckpoints Â» NoClassDefFound
  ZooKeeperCompletedCheckpointStoreITCase.testEmptyState Â» NoClassDefFound Could...
  ZooKeeperCompletedCheckpointStoreITCase.testExceptionOnNoRetainedCheckpoints Â» NoClassDefFound
  ZooKeeperCompletedCheckpointStoreITCase.testGetAllCheckpoints Â» NoClassDefFound
  ZooKeeperCompletedCheckpointStoreITCase.<clinit>:40 Â» NoSuchMethod org.apache....
  ZooKeeperSubmittedJobGraphsStoreITCase.org.apache.flink.runtime.jobmanager.ZooKeeperSubmittedJobGraphsStoreITCase Â» NoClassDefFound
  ZooKeeperSubmittedJobGraphsStoreITCase.testConcurrentAddJobGraph Â» NoClassDefFound
  ZooKeeperSubmittedJobGraphsStoreITCase.<clinit>:58 Â» NoSuchMethod org.apache.f...
  ZooKeeperSubmittedJobGraphsStoreITCase.testRecoverJobGraphs Â» NoClassDefFound ...
  ZooKeeperSubmittedJobGraphsStoreITCase.testUpdateJobGraphYouDidNotGetOrAdd Â» NoClassDefFound
  ZooKeeperStateHandleStoreITCase.org.apache.flink.runtime.zookeeper.ZooKeeperStateHandleStoreITCase Â» NoClassDefFound
  ZooKeeperStateHandleStoreITCase.testAdd Â» NoClassDefFound Could not initialize...
  ZooKeeperStateHandleStoreITCase.testAddAlreadyExistingPath Â» NoClassDefFound C...
  ZooKeeperStateHandleStoreITCase.testAddDiscardStateHandleAfterFailure Â» NoClassDefFound
  ZooKeeperStateHandleStoreITCase.testAddWithCreateMode Â» NoClassDefFound Could ...
  ZooKeeperStateHandleStoreITCase.testGetAll Â» NoClassDefFound Could not initial...
  ZooKeeperStateHandleStoreITCase.testGetAllSortedByName Â» NoClassDefFound Could...
  ZooKeeperStateHandleStoreITCase.testGetAndExists Â» NoClassDefFound Could not i...
  ZooKeeperStateHandleStoreITCase.testGetNonExistingPath Â» NoClassDefFound Could...
  ZooKeeperStateHandleStoreITCase.testRemove Â» NoClassDefFound Could not initial...
  ZooKeeperStateHandleStoreITCase.testRemoveAndDiscardAllState Â» NoClassDefFound
  ZooKeeperStateHandleStoreITCase.testRemoveAndDiscardState Â» NoClassDefFound Co...
  ZooKeeperStateHandleStoreITCase.testRemoveWithCallback Â» NoClassDefFound Could...
  ZooKeeperStateHandleStoreITCase.testReplace Â» NoClassDefFound Could not initia...
  ZooKeeperStateHandleStoreITCase.<clinit>:66 Â» NoSuchMethod org.apache.flink.ru...
  ZooKeeperStateHandleStoreITCase.testReplaceNonExistingPath Â» NoClassDefFound C...
```

**Comment by aljoscha** [comment]
Good fix! The failures went unnoticed before, I guess?

**Comment by tillrohrmann** [comment]
Running the tests from within IntelliJ works fine without a problem. I guess it has something todo how failsafe `2.19` handles dependencies.

**Comment by tillrohrmann** [comment]
Couldn't find the problem.

**Comment by StephanEwen** [comment]
Could you reproduce the problem on your laptop?

**Comment by tillrohrmann** [comment]
I could reproduce it via maven on my machine. It is a bit odd since he complains that

```
org.apache.flink.runtime.util.ZooKeeperUtils.startCuratorFramework(Lorg/apache/flink/configuration/Configuration;)Lorg/apache/curator/framework/CuratorFramework
```

Even though `ZooKeeperUtils` is in `flink-runtime`. Maybe it has something to do with the shading and that `org.apache.curator.framework.CuratorFramework` has been relocated?

**Comment by tillrohrmann** [comment]
Reverting back to version `2.17` it works again (at least the plugin does not complain about the `NoSuchMethodError`).

**Comment by aljoscha** [comment]
But maybe it only works since the exceptions are silently ignored and not forwarded?

**Comment by mxm** [comment]
If we can't resolve issues with the Failsafe plugin, we could switch to using the Surefire plugin also for Integration tests. Actually, the only benefit of the Failsafe plugin is that it enables to use different phases to reuse test infrastructure that is costly, e.g. `pre-integration-test`, `post-integration-test`, `integration-test`, `verify`. However, we only use the `integration-test` phase. We don't have any special code in the `verify` phase, other than Failsafe's own mechanism to check for test failures which seems to be broken.

**Comment by mxm** [comment]
@aljoscha Yes, I think so too :)

**Comment by tillrohrmann** [comment]
The question is whether this bug was introduced with version `2.18.1` or whether it was already there in version `2.17`. We originally bumped the version to `2.18` in order to allow retries for the `ElasticSearchSinkITCase`. But if it works with the Surefire plugin, then we can also do this.

**Comment by StephanEwen** [comment]
In the surefire JIRA, the "silently ignore exceptions" bug is tagged to affect 2.18, not 2.17, so it may be good.

How about:
  - Checking if using surefire solves things
  - If not, use failsafe 2.17 making sure it is not affected

**Comment by aljoscha** [comment]
👍 and make sure that the tests were not silently failing with 2.17

**Comment by mxm** [comment]
I just replaced Failsafe with Surefire. Also updated the version of Surefire in a separate commit to see if the classpath issues occur there as well (after all it's the same Apache project).

**Comment by mxm** [comment]
Also pushed a version to my local Travis branch with some deliberately failing tests and debug output to see if the above tests are executed correctly (and don't fail silently).

**Comment by StephanEwen** [comment]
Thanks @mxm ! Eagerly looking forward to the results...

**Comment by markreddy** [comment]
I took a look at the root issue of upgrading to 2.19.1. I'm able to reliably reproduce this issue on my laptop. 

When I bump the version I get the same as @tillrohrmann 
`java.lang.NoSuchMethodError:
org.apache.flink.runtime.util.ZooKeeperUtils.startCuratorFramework(Lorg/apache/flink/configuration/Configuration;)Lorg/apache/curator/framework/CuratorFramework`

When running the build in debug mode for both 2.18.1 and 2.19.1 I observed some differences in the classpath. 

**2.18.1**
`[DEBUG] boot(compact) classpath:  surefire-booter-2.18.1.jar  surefire-api-2.18.1.jar  test-classes  classes  flink-core-1.1-SNAPSHOT.jar.....`

**2.19.1**
`[DEBUG] boot(compact) classpath:  surefire-booter-2.19.1.jar  surefire-api-2.19.1.jar  test-classes  flink-runtime_2.10-1.1-SNAPSHOT.jar  flink-core-1.1-SNAPSHOT.jar.....`

So 2.19.1 has changed behaviour. What is loaded onto the classpath differs, in 2.19.1 instead of loading target/classes it loads the actual built jar. https://issues.apache.org/jira/browse/SUREFIRE-855 confirms this. 

The issue with this is the final jar has curator shaded while the test classes are looking for the unshaded version of curator, as shown by the debug output:
`Lorg/apache/curator/framework/CuratorFramework`

If @mxm can get everything working on a lower version thats the easiest solution. If not or we want to proceed with moving up in version, at least we know the root of the issue and can work from there....

**Comment by mxm** [comment]
Thanks for looking into the problem and providing a detailed explanation @markreddy. I think we're good to go with the newest version of the Surefire plugin. I verified the tests 1) fail when errors occur 2) are actually run (added some debug output) 3) the number of tests/ITCases remains unchanged.

Just running one more time because I forgot to set the default of `reuseForks` to false for the integration tests. Reusing of forks doesn't work for some tests because of garbage collection problems (this was the same for the Failsafe plugin). Apparently almost all tests pass. So looking forward to merging this soon.

**Comment by mxm** [comment]
I get segfaults from RocksDB in my Travis tests:  https://travis-ci.org/mxm/flink/builds/131412162

Let's see how the builds here go. All in all, looks ready to be merged.

**Comment by mxm** [comment]
The Travis builds here also segfault in all RocksDB tests. I'm assuming these test failed silently in the past since I can't make any connection to the test plugin changes.

**Comment by mxm** [comment]
Merging...we need to fix the RocksDB issue afterwards. In the worst case, we'll comment out the relevant test cases for now. The test which seems to cause the segfaults is `EventTimeWindowCheckpointingITCase`.
